/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as CapacityBuildingRouteImport } from './routes/capacity-building'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalksPressIndexRouteImport } from './routes/talks-press.index'
import { Route as SelectedWorksIndexRouteImport } from './routes/selected-works.index'
import { Route as TalksPressSlugRouteImport } from './routes/talks-press.$slug'
import { Route as SelectedWorksSlugRouteImport } from './routes/selected-works.$slug'

const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacityBuildingRoute = CapacityBuildingRouteImport.update({
  id: '/capacity-building',
  path: '/capacity-building',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksPressIndexRoute = TalksPressIndexRouteImport.update({
  id: '/talks-press/',
  path: '/talks-press/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectedWorksIndexRoute = SelectedWorksIndexRouteImport.update({
  id: '/selected-works/',
  path: '/selected-works/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksPressSlugRoute = TalksPressSlugRouteImport.update({
  id: '/talks-press/$slug',
  path: '/talks-press/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectedWorksSlugRoute = SelectedWorksSlugRouteImport.update({
  id: '/selected-works/$slug',
  path: '/selected-works/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capacity-building': typeof CapacityBuildingRoute
  '/research': typeof ResearchRoute
  '/selected-works/$slug': typeof SelectedWorksSlugRoute
  '/talks-press/$slug': typeof TalksPressSlugRoute
  '/selected-works/': typeof SelectedWorksIndexRoute
  '/talks-press/': typeof TalksPressIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capacity-building': typeof CapacityBuildingRoute
  '/research': typeof ResearchRoute
  '/selected-works/$slug': typeof SelectedWorksSlugRoute
  '/talks-press/$slug': typeof TalksPressSlugRoute
  '/selected-works': typeof SelectedWorksIndexRoute
  '/talks-press': typeof TalksPressIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capacity-building': typeof CapacityBuildingRoute
  '/research': typeof ResearchRoute
  '/selected-works/$slug': typeof SelectedWorksSlugRoute
  '/talks-press/$slug': typeof TalksPressSlugRoute
  '/selected-works/': typeof SelectedWorksIndexRoute
  '/talks-press/': typeof TalksPressIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/capacity-building'
    | '/research'
    | '/selected-works/$slug'
    | '/talks-press/$slug'
    | '/selected-works/'
    | '/talks-press/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/capacity-building'
    | '/research'
    | '/selected-works/$slug'
    | '/talks-press/$slug'
    | '/selected-works'
    | '/talks-press'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/capacity-building'
    | '/research'
    | '/selected-works/$slug'
    | '/talks-press/$slug'
    | '/selected-works/'
    | '/talks-press/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CapacityBuildingRoute: typeof CapacityBuildingRoute
  ResearchRoute: typeof ResearchRoute
  SelectedWorksSlugRoute: typeof SelectedWorksSlugRoute
  TalksPressSlugRoute: typeof TalksPressSlugRoute
  SelectedWorksIndexRoute: typeof SelectedWorksIndexRoute
  TalksPressIndexRoute: typeof TalksPressIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacity-building': {
      id: '/capacity-building'
      path: '/capacity-building'
      fullPath: '/capacity-building'
      preLoaderRoute: typeof CapacityBuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks-press/': {
      id: '/talks-press/'
      path: '/talks-press'
      fullPath: '/talks-press/'
      preLoaderRoute: typeof TalksPressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selected-works/': {
      id: '/selected-works/'
      path: '/selected-works'
      fullPath: '/selected-works/'
      preLoaderRoute: typeof SelectedWorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks-press/$slug': {
      id: '/talks-press/$slug'
      path: '/talks-press/$slug'
      fullPath: '/talks-press/$slug'
      preLoaderRoute: typeof TalksPressSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selected-works/$slug': {
      id: '/selected-works/$slug'
      path: '/selected-works/$slug'
      fullPath: '/selected-works/$slug'
      preLoaderRoute: typeof SelectedWorksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CapacityBuildingRoute: CapacityBuildingRoute,
  ResearchRoute: ResearchRoute,
  SelectedWorksSlugRoute: SelectedWorksSlugRoute,
  TalksPressSlugRoute: TalksPressSlugRoute,
  SelectedWorksIndexRoute: SelectedWorksIndexRoute,
  TalksPressIndexRoute: TalksPressIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
